from tkinter import*
import sqlite3
import tkinter
w=tkinter.Tk()
w.geometry('1360x1405')
w.resizable(0,0)
c=sqlite3.connect("base.db")
c.execute('create table IF NOT EXISTS employ1(id text,password text)')
c.execute("insert into employ1 values(textvar,textvar)")
w.configure(background="#ffe39f")
f1=Frame(w,width=400,height=400,bg="#ae5a41")
f1.place(x=780,y=180)
l1=Label(f1,text="USERNAME:",font=("times new roman",15,"bold"),bg="#ae5a41",fg="blue")
l1.place(x=30,y=100)
textvar=StringVar()
e1=Entry(f1,font=("times new roman",15,"bold"),textvariable=textvar)
e1.place(x=153,y=100)
l2=Label(f1,text="PASSWORD:",font=("times new roman",15,"bold"),bg="#ae5a41",fg="blue")
l2.place(x=30,y=180)
textvar1=StringVar()
e2=Entry(f1,font=("times new roman",15,"bold"),show="*",textvariable=textvar1)
e2.place(x=153,y=180)
b1=tkinter.Button(f1,text='LOGIN',bg="green",font=("times new roman",14,"bold"),border=0,relief=RAISED)
b1.place(x=166,y=250)
l3=Label(f1,text="Don't have an account? sign'up here",font=("times new roman",10),bg="#ae5a41",fg="black")
l3.place(x=67,y=330)
b2=tkinter.Button(f1,text='sign up',bg="green",font=("times new roman",10),border=0,relief=RAISED)
b2.place(x=270,y=330)
img=PhotoImage(file="16.png")
l4=tkinter.Label(w,image=img,border=0,relief=FLAT)
l4.place(x=40,y=60)

w.mainloop()
